### ISSUE TITLE
Issue with ios

### ISSUE THREAD

**Issue by Korefey** [customerio/customerio-flutter#132] opened 2024-07-27 15:19 UTC
Hi everyone.
I have implemented the package for android and it works fine.
But I have received an issue with ios.
Can you please explain how to fix it.

Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): Cycle inside Runner; building could produce unreliable results.
Cycle details:
→ That command depends on command in Target 'Runner': script phase “[CP] Copy Pods Resources”
○ Target 'Runner'
○ That command depends on command in Target 'Runner': script phase “[CP] Embed Pods Frameworks”
○ Target 'Runner'
○ That command depends on command in Target 'Runner': script phase “Thin Binary”
○ Target 'Runner' has process command with output '/Users/dev/Documents/Flutter/Emery/emery-mobile-app/build/ios/Debug-iphoneos/Runner.app/Info.plist'
○ Target 'Runner' has copy command from '/Users/dev/Documents/Flutter/Emery/emery-mobile-app/build/ios/Debug-iphoneos/NotificationServiceExtension.appex' to '/Users/dev/Documents/Flutter/Emery/emery-mobile-app/build/ios/Debug-iphoneos/Runner.app/PlugIns/NotificationServiceExtension.appex'
○ Target 'Runner' has copy command from '/Users/dev/Documents/Flutter/Emery/emery-mobile-app/ios/Flutter/AppFrameworkInfo.plist' to '/Users/dev/Documents/Flutter/Emery/emery-mobile-app/build/ios/Debug-iphoneos/Runner.app/AppFrameworkInfo.plist'

**Comment by ami-aman** [comment] 2024-07-29 08:12
Hi @Korefey 

Sorry to hear that you're experiencing this. 

The “Cycle inside Runner” error could be possibly due to cyclic dependencies among your build phases or due to derived data or conflicts in pod dependencies. By fixing these, you should be able to resolve the issue.

Although this issue appears to be related to configuration or implementation rather than our SDK, I am happy to assist you. Here are some suggestions that might help you troubleshoot the problem:

- Clean and rebuild the project : In Xcode, go to `Product` > `Clean Build Folder` 
- Remove Derived Data : In terminal, run `rm -rf ~/Library/Developer/Xcode/DerivedData` 
- Clean the project : `flutter clean`
- Check Podfile : Ensure that there are no conflicts or redundant entries
- Update dependencies & Re-install Pods : Run `pod install --repo-update` in `ios` directory 
- Rebuild flutter project : Run `flutter pub get` and `flutter build ios` 

I also found this [SOF question](https://stackoverflow.com/questions/77138968/handling-cycle-inside-runner-building-could-produce-unreliable-results-after-up) that looks relevant to the issue, in case it helps.

Please let us know if you are still experiencing the issue. It would be helpful if you could provide additional details such as:
- Steps to reproduce
- Xcode, flutter and `customerio-flutter` version in use
- Podfile
- AppDelegate
- Logs, if any 
- Minimal reproducible app

**Comment by Korefey** [comment] 2024-07-29 16:16
Hi @ami-aman 
I created new project, full filled all recommendations from manual and also received some issues.
Please check it on github https://github.com/Korefey/customer_ios

**Comment by ami-aman** [comment] 2024-07-29 18:57
Hi @Korefey 

Sorry to hear that despite following the recommendations, you are still experiencing issues. I appreciate you sharing a reproducible app. I will review your GitHub repository and get back to you as soon as possible with feedback or solutions. 

In the meantime, please feel free to add any additional details here if you have them.

**Comment by ami-aman** [comment] 2024-07-31 12:44
Hey @Korefey 

Thank you for sharing the demo app. I was able to reproduce the issue and resolve it by making adjustments to the build phases of your project. Below is a screenshot of the correct order of the build phases that helped resolve the issue. I hope this helps.

<img width="852" alt="Screenshot 2024-07-31 at 4 36 26 PM" src="https://github.com/user-attachments/assets/77010e7d-db9e-42c3-b90e-1da04bfde0bf">

![Simulator Screenshot - iPhone 15 Pro - 2024-07-31 at 16 34 10](https://github.com/user-attachments/assets/baaaf7ee-214a-44fd-9c82-d8df688272ef)

You may also refer our [flutter sample app](https://github.com/customerio/customerio-flutter/tree/main/apps/amiapp_flutter) for more reference.  

Since the issue is related to project configuration and not our SDK, I will close this ticket. Please feel free to reopen it or open a new issue if you have any other queries related to our SDK.

**Closed by ami-aman** 2024-07-31 12:44 UTC
